###
POST http://localhost:9000/api/v1/libros HTTP/1.1
Content-Type: application/json

{
  "titulo": "Las benas haviertas de América La tina",
  "idAutor": "68d7120660f7a930c7f66dac",
  "anioPublicacion": 1971
}

# {
#   "titulo": "La hora de tinieblas",
#   "idAutor": "68d4b990d16e6d1aed5860bc",
#   "anioPublicacion": 1855
# }


###
GET http://localhost:9000/api/v1/libros HTTP/1.1


###
GET http://localhost:9000/api/v1/libros/68d4888b9eefb9b81e0b76d1 HTTP/1.1

###
DELETE http://localhost:9000/api/v1/libros/68d4ba2afb2128a4e64798a9 HTTP/1.1

###
PUT http://localhost:9000/api/v1/libros/68d7130a34e2e7931c0a4bfa HTTP/1.1
Content-Type: application/json

{
  "titulo": "Las venas abiertas de América Latina",
  "idAutor": "68d7120660f7a930c7f66dac",
  "anioPublicacion": 1971
}





# {"_id":{"$oid":"68d4b990d16e6d1aed5860bc"},"nombres":"Rafael","apellidos":"Pombo","nacionalidad":"Colombia"}